# Generated by Django 6.0.3 on 2026-04-02 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pendingregistration',
            old_name='name',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='pendingregistration',
            name='last_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='pendingregistration',
            name='username',
            field=models.CharField(default='', max_length=150),
            preserve_default=False,
        ),
    ]
