# Generated by Django 6.0.3 on 2026-04-07 13:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_passwordresetotp'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pendingregistration',
            name='role',
            field=models.CharField(choices=[('patient', 'Patient'), ('pharmacist', 'Pharmacist'), ('physician', 'Physician'), ('nurse', 'Nurse'), ('other_health_professional', 'Other Health Professional')], default='patient', max_length=30),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('patient', 'Patient'), ('pharmacist', 'Pharmacist'), ('physician', 'Physician'), ('nurse', 'Nurse'), ('other_health_professional', 'Other Health Professional')], default='patient', max_length=30)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
