# Generated by Django 6.0.3 on 2026-04-09 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_pendingregistration_role_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pendingregistration',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='pendingregistration',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='pendingregistration',
            name='password',
        ),
        migrations.RemoveField(
            model_name='pendingregistration',
            name='username',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='first_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='last_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='preferred_name',
            field=models.CharField(blank=True, help_text='What should Rx call you?', max_length=150),
        ),
    ]
