# Generated by Django 6.0.3 on 2026-04-09 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_migrate_existing_users_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pendingregistration',
            name='role',
        ),
    ]
