# Generated by Django 6.0.3 on 2026-04-22 09:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_seed_subscription_plans'),
    ]

    operations = [
        migrations.AddField(
            model_name='trusteddevice',
            name='last_used',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
