# Generated by Codex on 2026-04-25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_trusteddevice_last_used'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='age_range',
            field=models.CharField(
                blank=True,
                choices=[
                    ('under_18', 'Under 18'),
                    ('18_24', '18-24'),
                    ('25_34', '25-34'),
                    ('35_44', '35-44'),
                    ('45_54', '45-54'),
                    ('55_64', '55-64'),
                    ('65_plus', '65+'),
                ],
                default='25_34',
                max_length=20,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(
                blank=True,
                choices=[
                    ('male', 'Male'),
                    ('female', 'Female'),
                ],
                default='male',
                max_length=10,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
