# Generated by Codex on 2026-04-25

from datetime import timedelta
from django.db import migrations, models
from django.utils import timezone


def split_otp_and_retention_expiry(apps, schema_editor):
    PendingRegistration = apps.get_model('accounts', 'PendingRegistration')
    for pending in PendingRegistration.objects.all():
        pending.otp_expires_at = pending.expires_at
        pending.expires_at = pending.created_at + timedelta(days=30)
        pending.save(update_fields=['otp_expires_at', 'expires_at'])


def restore_single_expiry(apps, schema_editor):
    PendingRegistration = apps.get_model('accounts', 'PendingRegistration')
    for pending in PendingRegistration.objects.all():
        pending.expires_at = pending.otp_expires_at or timezone.now()
        pending.save(update_fields=['expires_at'])


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_userprofile_demographics'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendingregistration',
            name='otp_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.RunPython(split_otp_and_retention_expiry, restore_single_expiry),
    ]
