# Generated by Codex for conversation context support.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shodic', '0002_conversation_manual_updated_at_remove_message_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='patient_sex',
            field=models.CharField(
                blank=True,
                choices=[('male', 'Male'), ('female', 'Female')],
                default='',
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name='conversation',
            name='pregnancy_status',
            field=models.CharField(
                blank=True,
                choices=[
                    ('not_applicable', 'Not applicable'),
                    ('not_pregnant_or_breastfeeding', 'Not pregnant or breastfeeding'),
                    ('pregnant', 'Pregnant'),
                    ('breastfeeding', 'Breastfeeding'),
                    ('unsure', 'Unsure'),
                ],
                default='',
                max_length=40,
            ),
        ),
        migrations.AddField(
            model_name='conversation',
            name='role',
            field=models.CharField(
                choices=[
                    ('patient', 'Patient'),
                    ('pharmacist', 'Pharmacist'),
                    ('physician', 'Physician'),
                    ('nurse', 'Nurse'),
                    ('other', 'Other health professional'),
                ],
                default='patient',
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name='conversation',
            name='subject',
            field=models.CharField(
                choices=[
                    ('self', 'Myself'),
                    ('other_patient', 'Another patient'),
                    ('general', 'General information'),
                ],
                default='self',
                max_length=30,
            ),
        ),
    ]
