services:
  - type: web
    name: rxchat-backend
    runtime: python
    rootDir: backend
    buildCommand: "./build.sh"
    startCommand: "gunicorn config.wsgi:application"
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        sync: false
      - key: ALLOWED_ORIGINS
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: DEEPSEEK_API_KEY
        sync: false
      - key: BREVO_API_KEY
        sync: false
      - key: BREVO_SENDER_EMAIL
        sync: false
      - key: BREVO_SENDER_NAME
        value: "RxChat"
      - key: PYTHON_VERSION
        value: "3.11.12"
