services:
  - type: web
    name: rxchat-backend
    runtime: python
    rootDir: backend
    buildCommand: "./build.sh"
    startCommand: "python manage.py collectstatic --noinput && python manage.py adopt_chat_migrations_for_rxchat && python manage.py migrate && gunicorn config.wsgi:application"
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        sync: false
      - key: ALLOWED_ORIGINS
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: OPENROUTER_API_KEY
        sync: false
      - key: OPENROUTER_BASE_URL
        value: "https://openrouter.ai/api/v1"
      - key: OPENROUTER_MODEL
        value: "openai/gpt-oss-120b:free"
      - key: QDRANT_URL
        sync: false
      - key: QDRANT_API_KEY
        sync: false
      - key: QDRANT_COLLECTION
        value: "rxchat"
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: BREVO_API_KEY
        sync: false
      - key: BREVO_SENDER_EMAIL
        sync: false
      - key: BREVO_SENDER_NAME_RXCHAT
        value: "RxChat"

      - key: PYTHON_VERSION
        value: "3.12.3"
