# Generated by Django 6.0.3 on 2026-04-26 13:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_message_attachments'),
    ]

    operations = [
        migrations.CreateModel(
            name='IngestionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('nafdac', 'NAFDAC'), ('openfda', 'OpenFDA'), ('neml', 'NEML'), ('nhia_stg', 'NHIA STG'), ('who', 'WHO EML'), ('nnmda', 'NNMDA'), ('all', 'All')], db_index=True, max_length=30)),
                ('action', models.CharField(db_index=True, max_length=50)),
                ('status', models.CharField(db_index=True, max_length=30)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ScrapeProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('nafdac', 'NAFDAC'), ('openfda', 'OpenFDA'), ('neml', 'NEML'), ('nhia_stg', 'NHIA STG'), ('who', 'WHO EML'), ('nnmda', 'NNMDA')], max_length=30, unique=True)),
                ('progress_data', models.JSONField(blank=True, default=dict)),
                ('last_run', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['source'],
            },
        ),
        migrations.CreateModel(
            name='SourceFileUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('nafdac', 'NAFDAC'), ('openfda', 'OpenFDA'), ('neml', 'NEML'), ('nhia_stg', 'NHIA STG'), ('who', 'WHO EML'), ('nnmda', 'NNMDA')], max_length=30)),
                ('file', models.FileField(upload_to='source_uploads/')),
                ('description', models.TextField(blank=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('processed', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='RawSourceData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('nafdac', 'NAFDAC'), ('openfda', 'OpenFDA'), ('neml', 'NEML'), ('nhia_stg', 'NHIA STG'), ('who', 'WHO EML'), ('nnmda', 'NNMDA')], db_index=True, max_length=30)),
                ('source_id', models.CharField(max_length=255)),
                ('raw_data', models.JSONField(default=dict)),
                ('file_name', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['source', 'source_id'],
                'permissions': [('can_run_ingestion', 'Can run ingestion tasks')],
                'constraints': [models.UniqueConstraint(fields=('source', 'source_id'), name='unique_raw_source_record')],
            },
        ),
        migrations.CreateModel(
            name='DrugChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chunk_index', models.PositiveIntegerField()),
                ('text', models.TextField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('qdrant_point_id', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('embedded_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('raw_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='chat.rawsourcedata')),
            ],
            options={
                'ordering': ['raw_source', 'chunk_index'],
                'constraints': [models.UniqueConstraint(fields=('raw_source', 'chunk_index'), name='unique_chunk_per_raw_source')],
            },
        ),
    ]
