# Generated by Django 6.0.3 on 2026-04-26 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_ingestionlog_scrapeprogress_sourcefileupload_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='drugchunk',
            options={'ordering': ['raw_source', 'chunk_index'], 'verbose_name': 'drug chunk', 'verbose_name_plural': 'drug chunks'},
        ),
        migrations.AlterModelOptions(
            name='ingestionlog',
            options={'ordering': ['-created_at'], 'verbose_name': 'ingestion log', 'verbose_name_plural': 'ingestion logs'},
        ),
        migrations.AlterModelOptions(
            name='rawsourcedata',
            options={'ordering': ['source', 'source_id'], 'permissions': [('can_run_ingestion', 'Can run ingestion tasks')], 'verbose_name': 'raw data source', 'verbose_name_plural': 'raw data sources'},
        ),
        migrations.AlterModelOptions(
            name='scrapeprogress',
            options={'ordering': ['source'], 'verbose_name': 'scrape progress', 'verbose_name_plural': 'scrape progress'},
        ),
        migrations.AlterModelOptions(
            name='sourcefileupload',
            options={'ordering': ['-uploaded_at'], 'verbose_name': 'upload source file', 'verbose_name_plural': 'upload source files'},
        ),
        migrations.AlterField(
            model_name='ingestionlog',
            name='source',
            field=models.CharField(choices=[('nafdac', 'NAFDAC'), ('openfda', 'OpenFDA'), ('neml', 'NEML'), ('nhia_stg', 'NHIA STG'), ('who', 'WHO EML'), ('nnmda', 'NNMDA'), ('emdex', 'EMDEX'), ('all', 'All')], db_index=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='rawsourcedata',
            name='source',
            field=models.CharField(choices=[('nafdac', 'NAFDAC'), ('openfda', 'OpenFDA'), ('neml', 'NEML'), ('nhia_stg', 'NHIA STG'), ('who', 'WHO EML'), ('nnmda', 'NNMDA'), ('emdex', 'EMDEX')], db_index=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='scrapeprogress',
            name='source',
            field=models.CharField(choices=[('nafdac', 'NAFDAC'), ('openfda', 'OpenFDA'), ('neml', 'NEML'), ('nhia_stg', 'NHIA STG'), ('who', 'WHO EML'), ('nnmda', 'NNMDA'), ('emdex', 'EMDEX')], max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='sourcefileupload',
            name='source',
            field=models.CharField(choices=[('nafdac', 'NAFDAC'), ('openfda', 'OpenFDA'), ('neml', 'NEML'), ('nhia_stg', 'NHIA STG'), ('who', 'WHO EML'), ('nnmda', 'NNMDA'), ('emdex', 'EMDEX')], max_length=30),
        ),
    ]
