# Generated by Django 6.0.3 on 2026-04-14 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rxchat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
