# Generated by Django 6.0.3 on 2026-04-14 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rxchat', '0002_message_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='role_override',
            field=models.CharField(blank=True, help_text='Per-conversation role override (e.g. nurse, physician). If set, overrides the user profile role for this conversation only.', max_length=30, null=True),
        ),
    ]
